import { Subject } from "@/types/userTypes";


export const subjects: Subject[] = [
    { name: "Mathematics", img: "/images/Mathematics.jpg" },
    { name: "Science", img: "/images/Science.jpg" },
    { name: "Computer Science", img: "/images/Computer-Science.jpg" },
    { name: "Engineering", img: "/images/Engineering.jpg" },
    { name: "History", img: "/images/History.jpg" },
    { name: "Geography", img: "/images/Geography.jpeg" },
    { name: "Languages", img: "/images/Languages.jpg" },
    { name: "Literature", img: "/images/Literature.webp" },
    { name: "Arts", img: "/images/Arts.jpg" },
    { name: "Music", img: "/images/Music.jpg" },
    { name: "Physical Education", img: "/images/Physical-Education.webp" },
    { name: "Health and Wellness", img: "/images/Health-and-Wellness.png" },
    { name: "Business", img: "/images/Business.jpg" },
    { name: "Economics", img: "/images/Economics.png" },
    { name: "Finance", img: "/images/Finance.jpg" },
    { name: "Law", img: "/images/Law.webp" },
    { name: "Political Science", img: "/images/Political-Science.jpg" },
    { name: "Philosophy", img: "/images/Philosophy.webp" },
    { name: "Psychology", img: "/images/Psychology.jpg" },
    { name: "Sociology", img: "/images/Sociology.jpg" },
    { name: "Anthropology", img: "/images/Anthropology.jpg" },
    { name: "Environmental Studies", img: "/images/Environmental-Studies.jpg" },
    { name: "Religious Studies", img: "/images/Religious-Studies.svg" },
    { name: "Vocational Skills", img: "/images/Vocational-Skills.png" },
    { name: "Technology", img: "/images/Technology.jpg" },
    { name: "Media Studies", img: "/images/Media-Studies.jpg" },
    { name: "Communication", img: "/images/Communication.jpg" },
    { name: "Public Speaking", img: "/images/Public-Speaking.webp" },
    { name: "Creative Writing", img: "/images/Creative-Writing.jpeg" },
    { name: "Architecture", img: "/images/Architecture.jpg" },
];
